name: Expo CI/CD Workflow

# Trigger the workflow when there are changes pushed to the 'dev' branch
on:
  push:
    branches:
      - dev

jobs:
  check_expo:
    name: Check Expo Configuration
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Expo CLI globally if needed
      - name: Install Expo CLI
        run: npm install -g expo

      # Step 5: Check if the 'expo' package is installed in the project
      - name: Ensure Expo is installed
        run: |
          if ! npm list expo; then
            echo "Expo package not found, installing..."
            npm install expo
          fi

      # Step 6: Run Expo Doctor to validate the configuration
      - name: Run Expo Doctor
        run: |
          npx expo-doctor
          if [ $? -ne 0 ]; then
            echo "Expo Doctor failed, stopping the workflow."
            exit 1
          fi

  notify_server:
    name: Notify Server
    runs-on: ubuntu-latest
    needs: check_expo  # This job depends on 'check_expo'

    steps:
      # Step 1: Send API request to notify the server if 'check_expo' passes
      - name: Call API to notify server
        uses: curlimages/curl@v1
        with:
          entrypoint: /bin/sh
          args: |
            -c "curl -X POST https://api.example.com/notify"